---
name: upload-tencentcloud-cos-action

on: [push]

jobs:
  integration:
    name: Integration test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Upload file
        uses: ./
        with:
          secret_id: ${{ secrets.cos_secret_id }}
          secret_key: ${{ secrets.cos_secret_key }}
          bucketname_appid: ${{ secrets.cos_bucketname_appid }}
          region: ${{ secrets.cos_region }}
          localpath: /etc/ssl/misc
          cospath: update/etc/ssl/
          folder: yes